apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
spec:
  blocks:
    - cidr: "192.168.68.208/28"   # 192.168.68.208 - 192.168.68.223 (LB pool for services)
    - cidr: "192.168.68.200/32"   # External gateway
    - cidr: "192.168.68.202/32"   # Internal gateway
  allowFirstLastIPs: "No"  # Required in Cilium 1.16+ if reserving first/last IPs 
