apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: kubernetes-backend-security
spec:
  provider:
    kubernetes:
      remoteNamespace: security
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: kube-system
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-db
  namespace: security
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-backend-security
  target:
    name: pocket-id-db
    creationPolicy: Owner
    template:
      data:
        DB_CONNECTION_STRING: "postgres://{{ .LOGIN }}:{{ .PASSWORD }}@{{ .HOST }}:{{ .PORT }}/{{ .DATABASE_NAME }}?sslmode=disable"
  data:
    - secretKey: LOGIN
      remoteRef:
        key: pocket-id-db-user
        property: LOGIN
    - secretKey: PASSWORD
      remoteRef:
        key: pocket-id-db-user
        property: PASSWORD
    - secretKey: HOST
      remoteRef:
        key: pocket-id-db-user
        property: HOST
    - secretKey: PORT
      remoteRef:
        key: pocket-id-db-user
        property: PORT
    - secretKey: DATABASE_NAME
      remoteRef:
        key: pocket-id-db-user
        property: DATABASE_NAME
