apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocket-id-data
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: zfs-localpv
  volumeMode: Filesystem
