apiVersion: v1
kind: Secret
metadata:
  name: pocket-id-secret
  namespace: security
type: Opaque
stringData:
  ENCRYPTION_KEY: ENC[AES256_GCM,data:jFaqfM32Rj1zUOlsP9n/cNmf17DiUf3IHI8VXBwEIi+mZwOj52a9AOsiA14=,iv:INofN+6R+Y1h6X0DrgBuGBU6Eizhlit64jGPWwSiPBw=,tag:WnwYzE2Yqyk9nBLkzBvbEA==,type:str]
sops:
  age:
    - recipient: age14c4q9365tr9lrssdysjqamj4nxw82uexw7hmfnfrmegmjnu5y5kq0x97up
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3N0R3WGt1TnJXUmVkWUc0
        RTJhREQ5YWFaN1pUQ3JVL2VWM3daaHlNZWtrCk9SeFB6clJnNGxKU0h2bVdoU2pP
        aGs5U0NvM2QrNE9wRUdGVmxHRzdOb00KLS0tIFM4cmt6dDVZOG84c0w1bnFOeGcx
        S1VVTUhYR1hQVUpUS3o0Q1RJOEdkK3MKtwAP6MbVB6SvJsFISRJkUB/53PILFKQG
        y+1BuAKUH0eDEPEMqEnghQwo8ozRbKudckzaxsEyLN+SNBKwqDO7pg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-11T20:54:00Z"
  mac: ENC[AES256_GCM,data:gDkf6ffxA9CuTsjvnJHIClu95W68YbG8W/pnA6e7N0TU3vJBNAqI+UK1crSnJwt4JUw+uKCIfmTuS+B/uBco2hF8PWbJ9+J/mQsfYw2ou880SfOYErkC+hxitH5C397rExnIKiQbsXXHM4jBM3CzERkBY2QBUaLMuN+ay0rzCR4=,iv:G9mEyxlXpTuEhLDt0ERw7hO9XAMNj5yxIyDtbp+z+QI=,tag:wOodlpxHtMk6o3mesS/GQQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
