apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-internal
  namespace: gateway
spec:
  addresses:
  - type: IPAddress
    value: 10.0.50.202
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.saleem.us"
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.saleem.us"
      tls:
        certificateRefs:
          - name: cert-saleem
            kind: Secret
            group: "" # required
      allowedRoutes:
        namespaces:
          from: All
