apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
helmCharts:
  - name: dragonfly-operator
    repo: oci://ghcr.io/dragonflydb/dragonfly-operator/helm
    version: v1.5.0
    releaseName: dragonfly-operator
    namespace: databases
    valuesFile: values.yaml
commonAnnotations:
  argocd.argoproj.io/sync-wave: "-5"
