apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - pvc.yaml
  - dnsendpoint.yaml
  - route.yaml
helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts
    version: 4.6.2
    releaseName: qbittorrent
    namespace: media
    valuesFile: values.yaml
    includeCRDs: false
commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"
