apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: radarr
  namespace: media
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  endpoints:
    - dnsName: radarr.saleem.us
      recordType: CNAME
      targets:
        - external.saleem.us
