apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns
  namespace: networking
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:hxUbTzbOPvR/41DQ2zHg0VbzQPRZTBsOuxed5CfhcMCOIYg=,iv:loljD+gyJRMO78TDYUwRXwZLB8iWZgOiyK9LcWtEHgg=,tag:+H6WuLqlxcitVyHWfFYifA==,type:str]
sops:
  age:
    - recipient: age14c4q9365tr9lrssdysjqamj4nxw82uexw7hmfnfrmegmjnu5y5kq0x97up
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTmN0RHVPUWRXTC85MUYv
        a2Zya2V6SDhnOHZTMzFtd1kwak1hS21wK0VnCkdvVXRnUkt6Y0E0OHYybTd6bytJ
        dU85WlpvQWFhRjlHTE9xVjA5ejlVZkUKLS0tIG14aXJvTFZzYzhSUXBMQUU1Ly92
        bXNmUENyNllMNWxyQmJKamJZS09OVTgKpS2mVsyE2b8crRX5Qk/LvRYDxl4p9VFD
        /MP1mdReF4oZAcoVIK27hA92ZmBu3p2KerKAfLHt/SEtpe4F++eBYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-09T18:57:51Z"
  mac: ENC[AES256_GCM,data:CHTzLwloctoZ5UzLYfK9XE5mzMJsMwlBQKNKx3yaAw1pd2zOwIfOPxNM2GR6I1vtBsZ2uHFQnYi5vfEflVPrp8MewnJvY3wuToGskpDNS/J8ImNdqcMFRjkxFy0b5F9rVnHYqKSAgQ1mXC5YViSLn4bTa4F4s4fWoTjfrAyCI+Y=,iv:j+9bahS2cF3nR/ZiWNDbQ/6+h4/WBZvX8H+gHzlFiBU=,tag:wxYxcV12WMLi3/LCgM8Fhg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
