apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns
  namespace: cloudflare-dns
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:sBPCVfXSCEF5h4NwU3/7KJ0RBumtocD+YPCQD/JdExfPBgxlmPtyJeJxl5C7eZv4oaPZmck=,iv:9phHUd+dV7iZET9sVIVDumVdk7zjwgiheQwrRP+mTwQ=,tag:A44gBdjMffpUWBdrS5i7bw==,type:str]
sops:
  age:
    - recipient: age14c4q9365tr9lrssdysjqamj4nxw82uexw7hmfnfrmegmjnu5y5kq0x97up
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQUdNM3dudkRHMkUrZG5Q
        YW9kYzFnb3hjVmc1T3NZNTF1RHVOUGZhS1VzCkdkSVZOQ0ZRcWVKb3pqMnZDbEVt
        YldsWmdmelhNNkREMFAwVjF5REdWd0kKLS0tIHJWdTlCNVpLQTNtZ2pVTTMvUUxh
        Q1o5MFZvQm9tYnZaNkFsRTB2dVZkd28KZh220MolxWFCDzLnk3qdnq8BLXlzs2lQ
        xw0WiQwQDJrsXXlQnNKa9iCECi8Tls7ITqjXpD1e5YyZ7sz7Mang9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-10T20:35:17Z"
  mac: ENC[AES256_GCM,data:1EDOwIeyBOy4QM/a0GYpv2QB/9uQ0F5yEnIiJUM6qjunl05rkce1s7WWKJBGWG+NUqjXOKKbm0S6aqB1A0WzqwrKE0++LB5fyMUuM5DXYNvr6vtVyj9QYEK2PdPus4tr/mppEdxrEgn/fBVGP9VU43zrrGrlSkVTQI1w2/3//nA=,iv:GTLINldgih4Dfb7EGGZ5k5heG/jyMif8IGlpdB2MpDc=,tag:g1zF/rZq+qn+hlAhNsjoLw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
