apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns
  namespace: cloudflare-dns
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:8sc+t5MvewrT270oWki36/wIylUgj8oFjrDvnPN24kTM98k5qwsdO4D0j1L367hzcSfBRdQ=,iv:koo5dk2/wE8uOveS0BJAxgbJmgz6Yd7gcOJF9oOpj7k=,tag:J5FQsvLOxULHrIL680xHPQ==,type:str]
sops:
  age:
    - recipient: age14c4q9365tr9lrssdysjqamj4nxw82uexw7hmfnfrmegmjnu5y5kq0x97up
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQUdNM3dudkRHMkUrZG5Q
        YW9kYzFnb3hjVmc1T3NZNTF1RHVOUGZhS1VzCkdkSVZOQ0ZRcWVKb3pqMnZDbEVt
        YldsWmdmelhNNkREMFAwVjF5REdWd0kKLS0tIHJWdTlCNVpLQTNtZ2pVTTMvUUxh
        Q1o5MFZvQm9tYnZaNkFsRTB2dVZkd28KZh220MolxWFCDzLnk3qdnq8BLXlzs2lQ
        xw0WiQwQDJrsXXlQnNKa9iCECi8Tls7ITqjXpD1e5YyZ7sz7Mang9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-09T19:10:47Z"
  mac: ENC[AES256_GCM,data:hr0kdgbMrG7i914rgw1AyH6AkIJAMCicatCxIJ6XzXFq25bqScIF/1V2615Zla7KvOhv7JtSLXOsskIytSbnqawXs34P/3n8IxCmQA1VZ3HRu3AH17zk5FTBAACLg3YSMcFA3Hi6QBVEbA8P/A6Kye9J9HqBMI0myd/A/dDT1DI=,iv:M96Mq75cx5FyhWtaWC4kaOlsHXUxhFtLfvWwHk5yeRI=,tag:mlfDo3+IfdYLl8k1+tNCCg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
