apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:QDUOAbfaiO/eMS05XsC7kKpbhEL5R+EX837SUeqnH6q29a76ESAf7ZLRUYgBVEiMla3NHvM=,iv:8DcXRQMpgVMdxNK9H9IpXLi03TG2fcPdDJAfcbKOvCk=,tag:upa+MBi2aZlPLIscrdE5yQ==,type:str]
sops:
  age:
    - recipient: age14c4q9365tr9lrssdysjqamj4nxw82uexw7hmfnfrmegmjnu5y5kq0x97up
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZjk3ZVlOdFNlSFlIeS9W
        US9kbkhDSnhoWWdwRXRHN2RVdHRTMy8ydzJVCjk4d1pXekVUc0drNFI2alhvc3NZ
        L3V0TkpqOHBYN0RNY1lnb1JOZkJ3b00KLS0tIGEvMTFHYWhvVlVFd2hQbENUL3Z6
        RVJhOFF6WWNYcCs0elNQTENrbTFGY00K8FagiLVqBN7QpdA3EtAQhloIS9ektInm
        CeJP6D15KR4yXWVZ+oXy3jayKU98h0IlGpB9+EWqQsBTfEyASAMckQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-11T13:16:17Z"
  mac: ENC[AES256_GCM,data:4xEeRW5rJx0o3ePlKPDK59bJkDd8kmlifG8Pgr50ZQ+PlgA4kALOUoCwIj8ikRjIaVPgUAECoeeSF2bz7U49jEm73vWrz07IrFmnhdYcxfw3oB1vOiLZX93IUAYkZvcF/D191p3nADoPtUUUjGQTm03gf/5a6vJUgw7UiM7lgtI=,iv:9fH7ugOFkTRQiefnlViJGICjL0i+KJDjmAwP0B+hNdg=,tag:w2vr4bVK4IZtf6qjKhuUJA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
