apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: headlamp
  namespace: headlamp
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  endpoints:
    - dnsName: headlamp.saleem.us
      recordType: CNAME
      targets:
        - external.saleem.us
