apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ext-postgres-operator
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-backend
  target:
    name: ext-postgres-operator-secret
    creationPolicy: Owner
    template:
      data:
        POSTGRES_USER: "{{ .username }}"
        POSTGRES_PASS: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: postgres17-superuser
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: password
      remoteRef:
        key: postgres17-superuser
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
