apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: databases
resources:
  - secret-store.yaml
  - external-secret.yaml
  - rbac.yaml
  - crds
helmCharts:
  - name: ext-postgres-operator
    repo: https://movetokube.github.io/postgres-operator
    version: 3.0.0
    releaseName: ext-postgres-operator
    namespace: databases
    valuesFile: values.yaml
