tunnel: rpi5
credentials-file: /etc/cloudflared/credentials/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true
protocol: http2
loglevel: debug
transport-loglevel: debug
ingress:
  - hostname: photos.saleem.us
    service: http://immich-server.immich.svc.cluster.local:2283
    originRequest:
      logHeaders: true
      headers:
        - name: CF-Connecting-IP
        - name: X-Real-IP
        - name: CF-IPCountry
        - name: CF-Ray
        - name: CF-Visitor
        - name: CF-Device-Type
        - name: CF-IPCITY
        - name: CF-IPCONTINENT
        - name: CF-IPLATITUDE
        - name: CF-IPLONGITUDE
        - name: CF-IPREGION
        - name: X-Forwarded-For
        - name: Accept-Language
        - name: User-Agent
        - name: True-Client-IP
        - name: CF-IPCountry
        - name: CF-RAY
        - name: CF-Worker
        - name: CF-Client-Bot
        - name: CF-Bot-Score
        - name: CF-Challenge
        - name: CF-Bot-Management-Tag
  - hostname: headlamp.saleem.us
    service: http://headlamp.headlamp.svc.cluster.local:80
    originRequest:
      logHeaders: true
      headers:
        - name: CF-Connecting-IP
        - name: X-Real-IP
        - name: CF-IPCountry
        - name: CF-Ray
        - name: CF-Visitor
        - name: CF-Device-Type
        - name: CF-IPCITY
        - name: CF-IPCONTINENT
        - name: CF-IPLATITUDE
        - name: CF-IPLONGITUDE
        - name: CF-IPREGION
        - name: X-Forwarded-For
        - name: Accept-Language
        - name: User-Agent
        - name: True-Client-IP
        - name: CF-IPCountry
        - name: CF-RAY
        - name: CF-Worker
        - name: CF-Client-Bot
        - name: CF-Bot-Score
        - name: CF-Challenge
        - name: CF-Bot-Management-Tag
  - service: http_status:404
