apiVersion: v1
kind: Secret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
type: Opaque
stringData:
  credentials.json: ENC[AES256_GCM,data:JLJrSZ9SNABU18xCYm3+oZYy5opDaZKrSu1xNgdN+G2W+n0WajX2ldN4izHgw0fh4P1lTb0/q0cRdHNgfZWyyq3XIX15jCEbBFLaHsTxdIapCJAqL9RZBjCQyfHVo+JGHUACkYYn3V3kaNCEE9LEE5D6pf/z5l0ImfVOwb/s6u6mU+YZaygpP8k1znZRe/LinGKzFXPQE/ju6Qzklh0r/e20fKumXsENIbfIGMCmcg==,iv:/ssnfyJzZRiEmcRExXyS3VGf6bSwY5o+LNwMa0mNwjA=,tag:3ATc/7RhJIxU5WOD0zxn9A==,type:str]
sops:
  age:
    - recipient: age14c4q9365tr9lrssdysjqamj4nxw82uexw7hmfnfrmegmjnu5y5kq0x97up
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bzZHT0JHWlMvYjUxc1o5
        WEdldG4zV1dSNVFGSFpuTzZJYVRYUlJHaVhrCm11NE1oQjFUY0hjUG5iU24xMU9D
        dnNEMHUrYThEQlVvTlJLSHI3NjMwRFEKLS0tIG5iWWNENTkxUDZXWmdudnE0L1Z1
        MVo2M2RndkdySzFxaUZpeG8zYUhzKzQKWS00CgSlRXNHV9oUNwmfAdUiaVM1cD0v
        3bgL0jWSQdvrt3NSHwCQdoinFD+fuE6e1LNbXwCT/+vk6K9+K1SfmA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-11T03:18:24Z"
  mac: ENC[AES256_GCM,data:vzR8D+N4J71tgCcvemvcEv/Bg+4x2fOnpgcb6zwv9Vpoeo+vr76/eAPLLrINfTA7qyaGe1T/0SvmHRgfxPi3jNgEnwZYJ2BAt5nclH8q3fhxtxqQAGxiGfdIiQj60X3TqcQxouHVPZfkbsQWp1SE1RbskLv0JUgO/T8aaNNs6M0=,iv:DQDhdXSkhS8H8aTqQMdOnIF4IJES1MirI0YX2CfLYS0=,tag:HzaPgc0Y9KcGP6YM42SBHA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
