apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-media
  namespace: cloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Ti
  storageClassName: zfs-localpv
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-cache
  namespace: cloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: zfs-localpv
  volumeMode: Filesystem
