apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
  namespace: cloud
type: Opaque
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:PeQFI7qp4e0fPz1TGwT3kOeCS4cn95b9mw+t+qx+xrBhZaW8Yc3BClDWhONM+QIYKyLzNjO0ifU5b8Iil30RmQ==,iv:PDq2XHNzjAtNhnJYsykIkTQmUYA5e8ponebaEdI1qQY=,tag:e9JDYnQ6L0mEDMecplsNLg==,type:str]
sops:
  age:
    - recipient: age14c4q9365tr9lrssdysjqamj4nxw82uexw7hmfnfrmegmjnu5y5kq0x97up
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVU5NMG9YbFF1akpPbVhY
        MEdWMU9uUEc2NDk3YlJvczArRVN6TWo2empvCm91N2FyMUJJRmZualErRVJQS0ZX
        aFBSSWNBczZndVlGdHZud1lLREFuSDgKLS0tIEhFcjZjRzBxY1VUWVZrSGJHT3Ez
        U2lLNlVzZVo4ZjJNankxVFpEelJhdk0K1lUJ954MBDJp/r1/mjuLoVGPROdCKRRA
        a3exVBImi6ETI1oebIy6khXXkolitBVC/E7x139guERLoTZ/0OCHGw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-11T20:41:49Z"
  mac: ENC[AES256_GCM,data:DYctZI/lmrq6y+WphbHOeue8FiUfvuWZeg74sdL8/QzMUvccMt5y/d9G6rGl9bjfB/gzXFMameRFRDrO7die7fWJWRZOf2U1T1HKaEn9F4M4mlHtraZHKMC5/d4c3Y/ZNrY7Qllesu7VXnU3Aod+qsL63pMd6GilLqQikXEzk8Q=,iv:srVMqueZBRoijANPVUzMwbzqFYd0Azf/20x04QeBvS0=,tag:H152rMExfcySiOfpT5e9Gw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
