controllers:
  main:
    containers:
      main:
        image:
          tag: v2.6.3

immich:
  persistence:
    library:
      existingClaim: immich-library

valkey:
  enabled: true
  controllers:
    main:
      containers:
        main:
          image:
            tag: 9.1-alpine
  persistence:
    data:
      enabled: true
      size: 1Gi
      type: persistentVolumeClaim
      storageClass: zfs-localpv
      accessMode: ReadWriteOnce

machine-learning:
  persistence:
    cache:
      enabled: true
      size: 10Gi
      type: persistentVolumeClaim
      storageClass: zfs-localpv
      accessMode: ReadWriteOnce

server:
  controllers:
    main:
      containers:
        main:
          env:
            DB_HOSTNAME: postgres-apps-rw.cloudnative-pg-cluster.svc
            DB_USERNAME: immich
            DB_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: immich-postgres-cred
                  key: password
            DB_DATABASE_NAME: immich
  ingress:
    main:
      enabled: false
