apiVersion: v1
kind: Secret
metadata:
  name: ext-postgres-operator-secret
  namespace: databases
type: Opaque
stringData:
  POSTGRES_USER: ENC[AES256_GCM,data:kBQqqRvn7yE=,iv:yuv4LdiFxSxAZGTkrxkvyJlf3B6k/qrnzL0cuDihhFA=,tag:ix2UMb8UGSg2tEF+jswWAA==,type:str]
  POSTGRES_PASS: ENC[AES256_GCM,data:brvCvtXcA9p5wQmm4PBOrfWHGHPbOQzo8942h/qByyvexzar2jmQMUukD9LZtH0aVaN3bQ8u1zpmc8tQBJJBhA==,iv:fARi1kfRWpglLcaqk6pxaCkppNVX1FAC0qMHbYAZ6/w=,tag:DN2oBH9qTVlAmQZ/Lmg3UA==,type:str]
sops:
  age:
    - recipient: age14c4q9365tr9lrssdysjqamj4nxw82uexw7hmfnfrmegmjnu5y5kq0x97up
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNGk1dUtjOEZZc2FpK0xL
        ZnY5M2ZHM3g4Ly9jWXFjQW5yRlZPVy9NY2gwCnlOUTlNUk1HY0xCV3o2cmRyTEV5
        UVRCVlFSbEc2aTgvL2NtejFzWWp3bU0KLS0tIFBzWFhUYXUxakNiYVcvMmxLOU11
        RExCYy94ZVhHVW5XNlFKVjJncHVZSHMKNvrrmn31Q9rbOz3yVTcqr3nR/KiE81VW
        YWyQJrZgWvLu83hU/J1C2SWrCmk22WnALB/lI7KnGgiE/ka6EXzCNw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-11T19:53:45Z"
  mac: ENC[AES256_GCM,data:QKwIOiTnajGZjiapi/lNNLtxK0/YpLRKLVuroY9WakLvdpkEdyh2mFQTcU34dxh5b1ke0frdIgOffCMpFJC2ljWGdK47k9P+CQBEGQaJ66PlKr2gJ0IOx/BEu9vExzXukxvCMmispnpgYy9grQ6cZHXxdezWpfXqBSeXI3tQnOE=,iv:7/8yxLQMcHyMJN62XZ/FjQOH9aIxAg1S4gSeugCwTvc=,tag:XaItVOrIxH3Y+fIEXXr9nQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
