apiVersion: v1
kind: Secret
metadata:
  name: ext-postgres-operator-secret
  namespace: databases
type: Opaque
stringData:
  POSTGRES_USER: ENC[AES256_GCM,data:kBQqqRvn7yE=,iv:yuv4LdiFxSxAZGTkrxkvyJlf3B6k/qrnzL0cuDihhFA=,tag:ix2UMb8UGSg2tEF+jswWAA==,type:str]
  POSTGRES_PASS: ENC[AES256_GCM,data:fnsCG7kCvbY=,iv:tB/ExDZ1lHtm/y5ldvuw4x355V0BZZiW3o7NBdHKaSU=,tag:0De1bgWbHMpudC1MGhsHLA==,type:str]
sops:
  age:
    - recipient: age14c4q9365tr9lrssdysjqamj4nxw82uexw7hmfnfrmegmjnu5y5kq0x97up
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNGk1dUtjOEZZc2FpK0xL
        ZnY5M2ZHM3g4Ly9jWXFjQW5yRlZPVy9NY2gwCnlOUTlNUk1HY0xCV3o2cmRyTEV5
        UVRCVlFSbEc2aTgvL2NtejFzWWp3bU0KLS0tIFBzWFhUYXUxakNiYVcvMmxLOU11
        RExCYy94ZVhHVW5XNlFKVjJncHVZSHMKNvrrmn31Q9rbOz3yVTcqr3nR/KiE81VW
        YWyQJrZgWvLu83hU/J1C2SWrCmk22WnALB/lI7KnGgiE/ka6EXzCNw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-11T19:51:01Z"
  mac: ENC[AES256_GCM,data:O6+rqi0m+968JsLBuC8SF3ux/QCQQHbCw9W0UPRYD2aUMa2WYWJohk52CjXr5VcgLHLrJuTgakQNBBM9ydYoaMwIrQBspTmwyZEvvsC6oPSQSRtoEj9G/ET3THCdSuQFJYjVjUTQg11SJk7RvbXwqH1cglakrlUCLV/FhGiZ86o=,iv:+McMdnM0cPtq339krZCWV53U6XIt/HOLpi3I0Yq18cs=,tag:+ee7/ZkS3psYX6+y7yA+5Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
