apiVersion: v1
kind: Secret
metadata:
  name: ext-postgres-operator-secret
  namespace: databases
type: Opaque
stringData:
  POSTGRES_USER: ENC[AES256_GCM,data:kBQqqRvn7yE=,iv:yuv4LdiFxSxAZGTkrxkvyJlf3B6k/qrnzL0cuDihhFA=,tag:ix2UMb8UGSg2tEF+jswWAA==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:KG3msPMWgvE=,iv:1KambIlv/BCs/rs+gLWokoy7o4S41T4J1roPfgOHWtY=,tag:1Cza1seFokpWBgvX3Uuuyg==,type:str]
sops:
  age:
    - recipient: age14c4q9365tr9lrssdysjqamj4nxw82uexw7hmfnfrmegmjnu5y5kq0x97up
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNGk1dUtjOEZZc2FpK0xL
        ZnY5M2ZHM3g4Ly9jWXFjQW5yRlZPVy9NY2gwCnlOUTlNUk1HY0xCV3o2cmRyTEV5
        UVRCVlFSbEc2aTgvL2NtejFzWWp3bU0KLS0tIFBzWFhUYXUxakNiYVcvMmxLOU11
        RExCYy94ZVhHVW5XNlFKVjJncHVZSHMKNvrrmn31Q9rbOz3yVTcqr3nR/KiE81VW
        YWyQJrZgWvLu83hU/J1C2SWrCmk22WnALB/lI7KnGgiE/ka6EXzCNw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-11T03:20:29Z"
  mac: ENC[AES256_GCM,data:U3dT1gJnnsjxLtxSYb0b/Z4AqbLiybyvL1uncNUig8M2ja9Me8i9P8NLLpCE/8Y3HjXe0vcijY7Iqm7m1T1uUd8tEz3SsrUGdCC5DKqHe/TZJRxyqg5qZDVh/lB8umxruQ89g0dXrmKQ0rnQaBjBHvrCrPGZKuzGas4iFbTwZlo=,iv:z281ohKRIb3St4DlOwFDck6UGgeSSPYCwMbIwFCgPkc=,tag:oSt3C86ow3Qsm5I418hOuQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
