apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: filebrowser
  namespace: cloud
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  endpoints:
    - dnsName: files.saleem.us
      recordType: CNAME
      targets:
        - external.saleem.us
