apiVersion: v1
kind: Secret
metadata:
  name: filebrowser-oidc-secret
  namespace: cloud
type: Opaque
stringData:
  FILEBROWSER_OIDC_CLIENT_ID: ENC[AES256_GCM,data:bRMYHxDRH7aEzWE0I5EezGAHd3sPuPZ/eOGOc24W/hFwf5vd,iv:h57Z1VeSJgSBh9czvMI5I2r/dls5JlT0e7ezBW9z+cY=,tag:r9dBxGQwpfVfdlqu5UbOGg==,type:str]
  FILEBROWSER_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:jzTzlGfvab1CyEgYhAFN7s5+ScsdSF7NF2MvwQ8em5Y=,iv:jo/LlRJWRqUzS9inqTuAI1NEjO53/hD/o2QxOzGoWIA=,tag:zXmFOW4c0ZKjcxycNTR6og==,type:str]
sops:
  age:
    - recipient: age14c4q9365tr9lrssdysjqamj4nxw82uexw7hmfnfrmegmjnu5y5kq0x97up
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UWRoWUFnRFVBd0VFdVd0
        clkwaGd4ODk1aTV0bWFqSXhIR0hPOFRzUjJRCkdHNzNicGZsT2IyRklwdlcwSEYv
        L2dxUXZtYnB2ZFhmSllSZ1pQOVJNK2cKLS0tIDVaaXJtQjlYNk9QL3VWdWRYZXdi
        RTlGZUNCQk5ldHEySFl1dFpFNEx1QXcKx7xLYSpBAphOR7c9x2Ty0C9CnFJFHRYu
        MzYmFP07mx3NRtqX+WGPpgtlxwTGM4BaOTWGar3PxD7pYx0xWu/jaA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-16T03:17:12Z"
  mac: ENC[AES256_GCM,data:hw7eT4TTOur3cp6FHGUUrTtTbZLSar49H+IXEKRlKsvhdv0BkV4wXJQma1D22Q3sWEa4+eYj/ok0Q1PDNVUlZzoHm887HW54W2hAzpi4beAZfHD5g0efCqCbLPLK7mvQVVLppNoSZlFwO1U2JUYUs+cHdHuK6GtXwX6015J2xqg=,iv:CkQrWxfIyTqh56+lrUfKAYzxI7/DYpvj5GioSoroQOA=,tag:Wf63OjvlWCuCSE6SkZd9vQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
