apiVersion: v1
kind: Secret
metadata:
  name: filebrowser-oidc-secret
  namespace: cloud
type: Opaque
stringData:
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:TGfkL4nuuWp1YyoS3oEeRQOHamSkIcbq30ngSKIZ5NY=,iv:yAB10TRRqVkLiQaxKmvaRUUIQtAPXRWFCaIpg8AL23Y=,tag:VnGo3DPF3vTMmYf1XIH2tQ==,type:str]
sops:
  age:
    - recipient: age14c4q9365tr9lrssdysjqamj4nxw82uexw7hmfnfrmegmjnu5y5kq0x97up
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UkFXcEFZcGpDMGxlVXdO
        WlZJU0JjSlJITGR4R1dpb3ptQlEzYWwzd2tzCmVEdzVIL2NnZXdaMTBoMm1PZmRm
        S1gvcmVtbkVDeXQxeGNzVFRLNTFVZHMKLS0tIDNPeVNGNHBnTmMrcDRSdFJNNEk5
        NXlsZzExeG1wZGdnM1c0TkI5M3BLNU0KUzkX/KcQBo6ywxdQ67d70mfa9u7IeXax
        Li0bKKEZbtUhRMzXeaAerPfaKiOX3U88rvPYtHdq8wCocaTJJYLgpA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-16T03:04:21Z"
  mac: ENC[AES256_GCM,data:QxZhGP/qNF/dFEj8+jOm1FJ3YCIyVLQqfvk4N0jzJ8JwVP46ZQGHoPT3l8yFPU0xiRpdp83VTlkYxP4738t7QlpymuLLuy26u/VJr0wMf0xh2gldsLXjjRD3dA5s5HOnqjF7zkBjxuJ+4icSVz1DFPygPNzUDfxiyIUvOwJ1ezc=,iv:aLWl4Fsxld2Y9UiDwC2ZBSLJ0nboUBKOLcayRz6BFsk=,tag:ADJBSSHDcUlyyDUPuMWTjg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
