controllers:
  main:
    containers:
      app:
        image:
          repository: gtstef/filebrowser
          tag: stable
        env:
          TZ: America/Denver
          FILEBROWSER_OIDC_CLIENT_ID:
            valueFrom:
              secretKeyRef:
                name: filebrowser-oidc-secret
                key: FILEBROWSER_OIDC_CLIENT_ID
          FILEBROWSER_OIDC_CLIENT_SECRET:
            valueFrom:
              secretKeyRef:
                name: filebrowser-oidc-secret
                key: FILEBROWSER_OIDC_CLIENT_SECRET
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /health
            port: 80
          readiness:
            enabled: true
            type: HTTP
            path: /health
            port: 80
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 1Gi

service:
  app:
    controller: main
    ports:
      http:
        port: 80

persistence:
  config:
    type: configMap
    name: filebrowser-config
    globalMounts:
      - path: /home/filebrowser/data/config.yaml
        subPath: config.yaml
        readOnly: true
  data:
    type: hostPath
    hostPath: /Data/Files
    globalMounts:
      - path: /files
  dropbox:
    type: hostPath
    hostPath: /Data/Dropbox
    globalMounts:
      - path: /dropbox
